export type Option = {
  name: string;
  type: string;
  required: boolean;
  description: string;
};

export type Command = {
  id: string;
  name: string;
  syntax: string;
  description: string;
  permission: string;
  permissionType: "admin" | "staff" | "everyone" | "perm";
  options: Option[];
};

export type Category = {
  id: string;
  title: string;
  description: string;
  commands: Command[];
};

export const categories: Category[] = [
  {
    id: "mod",
    title: "الإشراف",
    description: "أوامر الإدارة والعقوبات — تتطلب رتبة موظف + صلاحية Discord المحددة",
    commands: [
      {
        id: "mod-ban",
        name: "/mod ban",
        syntax: "/mod ban user:<عضو> [reason:<نص>] [delete_days:<0-7>]",
        description: "حظر عضو من السيرفر نهائياً، مع خيار حذف رسائله الأخيرة (من 0 إلى 7 أيام).",
        permission: "Ban Members",
        permissionType: "perm",
        options: [
          { name: "user", type: "عضو", required: true, description: "العضو المراد حظره" },
          { name: "reason", type: "نص", required: false, description: "سبب الحظر (يظهر في السجلات)" },
          { name: "delete_days", type: "رقم 0-7", required: false, description: "عدد أيام الرسائل المراد حذفها" },
        ],
      },
      {
        id: "mod-unban",
        name: "/mod unban",
        syntax: "/mod unban user_id:<معرّف> [reason:<نص>]",
        description: "فك حظر عضو باستخدام معرّف Discord الخاص به.",
        permission: "Ban Members",
        permissionType: "perm",
        options: [
          { name: "user_id", type: "معرّف", required: true, description: "معرّف Discord للعضو المحظور" },
          { name: "reason", type: "نص", required: false, description: "سبب فك الحظر" },
        ],
      },
      {
        id: "mod-kick",
        name: "/mod kick",
        syntax: "/mod kick user:<عضو> [reason:<نص>]",
        description: "طرد عضو من السيرفر دون حظره.",
        permission: "Kick Members",
        permissionType: "perm",
        options: [
          { name: "user", type: "عضو", required: true, description: "العضو المراد طرده" },
          { name: "reason", type: "نص", required: false, description: "سبب الطرد" },
        ],
      },
      {
        id: "mod-timeout",
        name: "/mod timeout",
        syntax: "/mod timeout user:<عضو> duration:<مثل 10m أو 1h> [reason:<نص>]",
        description: "كتم مؤقت لعضو لمدة محددة. يدعم صيغ مثل 10m، 1h، 2d.",
        permission: "Moderate Members",
        permissionType: "perm",
        options: [
          { name: "user", type: "عضو", required: true, description: "العضو المراد كتمه" },
          { name: "duration", type: "مدة", required: true, description: "مدة الكتم (مثال: 10m، 1h، 1d)" },
          { name: "reason", type: "نص", required: false, description: "سبب الكتم" },
        ],
      },
      {
        id: "mod-untimeout",
        name: "/mod untimeout",
        syntax: "/mod untimeout user:<عضو> [reason:<نص>]",
        description: "إلغاء الكتم المؤقت قبل انتهاء مدته.",
        permission: "Moderate Members",
        permissionType: "perm",
        options: [
          { name: "user", type: "عضو", required: true, description: "العضو المراد إلغاء كتمه" },
          { name: "reason", type: "نص", required: false, description: "سبب الإلغاء" },
        ],
      },
      {
        id: "mod-warn",
        name: "/mod warn",
        syntax: "/mod warn user:<عضو> reason:<نص>",
        description: "إصدار تحذير رسمي يُحتسب ضمن سلّم العقوبات التلقائي.",
        permission: "Moderate Members",
        permissionType: "perm",
        options: [
          { name: "user", type: "عضو", required: true, description: "العضو المراد تحذيره" },
          { name: "reason", type: "نص", required: true, description: "سبب التحذير" },
        ],
      },
      {
        id: "mod-warnings",
        name: "/mod warnings",
        syntax: "/mod warnings user:<عضو>",
        description: "عرض كل التحذيرات المسجّلة على عضو معيّن.",
        permission: "موظفين",
        permissionType: "staff",
        options: [
          { name: "user", type: "عضو", required: true, description: "العضو المراد عرض تحذيراته" },
        ],
      },
      {
        id: "mod-unwarn",
        name: "/mod unwarn",
        syntax: "/mod unwarn id:<رقم_التحذير>",
        description: "حذف تحذير معيّن برقمه.",
        permission: "موظفين",
        permissionType: "staff",
        options: [
          { name: "id", type: "رقم", required: true, description: "رقم التحذير المراد حذفه" },
        ],
      },
      {
        id: "mod-ladder",
        name: "/mod ladder",
        syntax: "/mod ladder count:<رقم> action:<timeout|kick|ban> [duration:<مثل 1h>]",
        description: "إعداد تصعيد تلقائي عند وصول عضو لعدد تحذيرات معيّن.",
        permission: "أدمن",
        permissionType: "admin",
        options: [
          { name: "count", type: "رقم", required: true, description: "عدد التحذيرات" },
          { name: "action", type: "اختيار", required: true, description: "timeout أو kick أو ban" },
          { name: "duration", type: "مدة", required: false, description: "مدة الكتم إن لزم" },
        ],
      },
      {
        id: "mod-purge",
        name: "/mod purge",
        syntax: "/mod purge amount:<1-100>",
        description: "حذف جماعي للرسائل الأخيرة في القناة الحالية.",
        permission: "Manage Messages",
        permissionType: "perm",
        options: [
          { name: "amount", type: "رقم 1-100", required: true, description: "عدد الرسائل" },
        ],
      },
      {
        id: "mod-lock",
        name: "/mod lock",
        syntax: "/mod lock [reason:<نص>]",
        description: "قفل القناة الحالية عن الكتابة.",
        permission: "Manage Channels",
        permissionType: "perm",
        options: [
          { name: "reason", type: "نص", required: false, description: "سبب القفل" },
        ],
      },
      {
        id: "mod-unlock",
        name: "/mod unlock",
        syntax: "/mod unlock [reason:<نص>]",
        description: "إعادة فتح القناة للكتابة.",
        permission: "Manage Channels",
        permissionType: "perm",
        options: [
          { name: "reason", type: "نص", required: false, description: "سبب إعادة الفتح" },
        ],
      },
      {
        id: "mod-slowmode",
        name: "/mod slowmode",
        syntax: "/mod slowmode seconds:<0-21600>",
        description: "ضبط Slowmode في القناة الحالية. ضع 0 لإيقافه.",
        permission: "Manage Channels",
        permissionType: "perm",
        options: [
          { name: "seconds", type: "رقم 0-21600", required: true, description: "الثواني بين الرسائل" },
        ],
      },
      {
        id: "mod-nickname",
        name: "/mod nickname",
        syntax: "/mod nickname user:<عضو> [nickname:<نص>]",
        description: "تغيير لقب عضو. اتركه فارغاً لإعادة الاسم الافتراضي.",
        permission: "Manage Nicknames",
        permissionType: "perm",
        options: [
          { name: "user", type: "عضو", required: true, description: "العضو" },
          { name: "nickname", type: "نص", required: false, description: "اللقب الجديد (حتى 32 حرف)" },
        ],
      },
    ],
  },
];
categories.push({
  id: "custom",
  title: "الأوامر المخصصة",
  description: "إنشاء اختصارات إدارية بكلمة واحدة — للموظفين والأدمن",
  commands: [
    {
      id: "custom-create",
      name: "/custom create",
      syntax: "/custom create trigger:<كلمة> action:<نوع> [action2] [timeout_duration] [purge_amount] [slowmode_seconds] [reply] [staff_only] [match]",
      description: "إنشاء أمر مختصر مخصص. الإجراءات: ban, unban, kick, timeout, untimeout, warn, unwarn, purge, lock, unlock, slowmode, nickname, reply, dm, role_add, role_remove.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "trigger", type: "نص", required: true, description: "الكلمة المختصرة" },
        { name: "action", type: "اختيار", required: true, description: "نوع الإجراء" },
        { name: "action2", type: "اختيار", required: false, description: "إجراء ثانٍ" },
        { name: "timeout_duration", type: "مدة", required: false, description: "مدة الكتم" },
        { name: "purge_amount", type: "رقم 1-100", required: false, description: "عدد الرسائل" },
        { name: "slowmode_seconds", type: "رقم", required: false, description: "ثواني البطيء" },
        { name: "reply", type: "نص", required: false, description: "نص الرد ({user} {reason} {moderator} {server})" },
        { name: "staff_only", type: "صح/خطأ", required: false, description: "موظفين فقط؟ (افتراضي صح)" },
        { name: "match", type: "نمط", required: false, description: "نمط المطابقة" },
      ],
    },
    {
      id: "custom-add-action",
      name: "/custom add-action",
      syntax: "/custom add-action trigger:<اسم> action:<نوع> [timeout_duration] [purge_amount] [slowmode_seconds] [text]",
      description: "إضافة إجراء إضافي لأمر مخصص موجود.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "trigger", type: "نص", required: true, description: "اسم الأمر" },
        { name: "action", type: "اختيار", required: true, description: "نوع الإجراء" },
        { name: "timeout_duration", type: "مدة", required: false, description: "مدة الكتم" },
        { name: "purge_amount", type: "رقم", required: false, description: "عدد الرسائل" },
        { name: "slowmode_seconds", type: "رقم", required: false, description: "ثواني البطيء" },
        { name: "text", type: "نص", required: false, description: "نص لـ reply/dm" },
      ],
    },
    {
      id: "custom-rename",
      name: "/custom rename",
      syntax: "/custom rename from:<الاسم_الحالي> to:<الاسم_الجديد>",
      description: "إعادة تسمية أمر مخصص.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "from", type: "نص", required: true, description: "الاسم الحالي" },
        { name: "to", type: "نص", required: true, description: "الاسم الجديد" },
      ],
    },
    {
      id: "custom-delete",
      name: "/custom delete",
      syntax: "/custom delete trigger:<اسم>",
      description: "حذف أمر مخصص نهائياً.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [{ name: "trigger", type: "نص", required: true, description: "اسم الأمر" }],
    },
    {
      id: "custom-list",
      name: "/custom list",
      syntax: "/custom list",
      description: "عرض كل الأوامر المخصصة في السيرفر.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [],
    },
    {
      id: "custom-info",
      name: "/custom info",
      syntax: "/custom info trigger:<اسم>",
      description: "عرض التفاصيل التقنية الكاملة لأمر مخصص.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [{ name: "trigger", type: "نص", required: true, description: "اسم الأمر" }],
    },
    {
      id: "custom-permission",
      name: "/custom permission",
      syntax: "/custom permission trigger:<اسم> staff_only:<صح/خطأ> [role:<رتبة>]",
      description: "تحديد من يستخدم الأمر. صلاحيات Discord الحقيقية تُفرض دائماً.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "trigger", type: "نص", required: true, description: "اسم الأمر" },
        { name: "staff_only", type: "صح/خطأ", required: true, description: "موظفين فقط؟" },
        { name: "role", type: "رتبة", required: false, description: "رتبة محددة" },
      ],
    },
    {
      id: "custom-install-arabic",
      name: "/custom install-arabic",
      syntax: "/custom install-arabic",
      description: "تثبيت مجموعة جاهزة من الأوامر المختصرة العربية الشائعة.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [],
    },
  ],
});
categories.push({
  id: "automod",
  title: "الحماية التلقائية",
  description: "AutoMod — طبقات الدفاع التلقائية",
  commands: [
    {
      id: "automod-word-add",
      name: "/automod word-add",
      syntax: "/automod word-add word:<نص> action:<العقوبة> [duration]",
      description: "إضافة كلمة محظورة مع عقوبة تلقائية.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "word", type: "نص", required: true, description: "الكلمة المحظورة" },
        { name: "action", type: "اختيار", required: true, description: "العقوبة" },
        { name: "duration", type: "مدة", required: false, description: "مدة الكتم" },
      ],
    },
    {
      id: "automod-word-remove",
      name: "/automod word-remove",
      syntax: "/automod word-remove word:<نص>",
      description: "حذف كلمة من القائمة المحظورة.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [{ name: "word", type: "نص", required: true, description: "الكلمة" }],
    },
    {
      id: "automod-words",
      name: "/automod words",
      syntax: "/automod words",
      description: "عرض كل الكلمات المحظورة.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [],
    },
    {
      id: "automod-spam",
      name: "/automod spam",
      syntax: "/automod spam enabled:<صح/خطأ> [messages:<3-20>] [window_seconds:<2-30>] [action]",
      description: "مكافحة السبام: رصد رسائل كثيرة في وقت قصير.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "enabled", type: "صح/خطأ", required: true, description: "تفعيل/إيقاف" },
        { name: "messages", type: "رقم 3-20", required: false, description: "عدد الرسائل" },
        { name: "window_seconds", type: "رقم 2-30", required: false, description: "النافذة الزمنية" },
        { name: "action", type: "اختيار", required: false, description: "العقوبة" },
      ],
    },
    {
      id: "automod-mentions",
      name: "/automod mentions",
      syntax: "/automod mentions limit:<2-20>",
      description: "حد أقصى للمنشنات في الرسالة الواحدة.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [{ name: "limit", type: "رقم 2-20", required: true, description: "الحد الأقصى" }],
    },
    {
      id: "automod-links",
      name: "/automod links",
      syntax: "/automod links block_links:<صح/خطأ> block_invites:<صح/خطأ>",
      description: "حظر الروابط العادية و/أو دعوات Discord.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "block_links", type: "صح/خطأ", required: true, description: "حظر الروابط" },
        { name: "block_invites", type: "صح/خطأ", required: true, description: "حظر الدعوات" },
      ],
    },
    {
      id: "automod-raid",
      name: "/automod raid",
      syntax: "/automod raid joins:<3-50> window_seconds:<5-120> [min_account_hours]",
      description: "مكافحة الغارات: رصد موجات انضمام غير طبيعية.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "joins", type: "رقم 3-50", required: true, description: "عدد الانضمامات" },
        { name: "window_seconds", type: "رقم 5-120", required: true, description: "النافذة الزمنية" },
        { name: "min_account_hours", type: "رقم", required: false, description: "حد عمر الحساب" },
      ],
    },
    {
      id: "automod-nuke",
      name: "/automod nuke",
      syntax: "/automod nuke channel_deletes:<2-20> role_deletes:<2-20> mass_bans:<2-20>",
      description: "حماية Nuke: حجر تلقائي للموظفين الذين يحذفون أو يحظرون بكميات كبيرة.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "channel_deletes", type: "رقم 2-20", required: true, description: "حد حذف القنوات" },
        { name: "role_deletes", type: "رقم 2-20", required: true, description: "حد حذف الرتب" },
        { name: "mass_bans", type: "رقم 2-20", required: true, description: "حد الحظر الجماعي" },
      ],
    },
    {
      id: "automod-status",
      name: "/automod status",
      syntax: "/automod status",
      description: "عرض ملخص إعدادات AutoMod الحالية.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [],
    },
  ],
});
categories.push({
  id: "config",
  title: "إعدادات السيرفر",
  description: "أوامر الإعداد الأساسية — للأدمن فقط",
  commands: [
    {
      id: "config-staff-role",
      name: "/config staff-role",
      syntax: "/config staff-role role:<رتبة>",
      description: "تحديد رتبة الموظفين الأساسية.",
      permission: "أدمن",
      permissionType: "admin",
      options: [{ name: "role", type: "رتبة", required: true, description: "رتبة الموظفين" }],
    },
    {
      id: "config-logs",
      name: "/config logs",
      syntax: "/config logs [mod:<قناة>] [general:<قناة>] [tickets:<قناة>]",
      description: "تحديد قنوات سجلات الإشراف والعامة والتذاكر.",
      permission: "أدمن",
      permissionType: "admin",
      options: [
        { name: "mod", type: "قناة", required: false, description: "سجلات الإشراف" },
        { name: "general", type: "قناة", required: false, description: "السجلات العامة" },
        { name: "tickets", type: "قناة", required: false, description: "سجلات التذاكر" },
      ],
    },
    {
      id: "config-command-role",
      name: "/config command-role",
      syntax: "/config command-role command:<مفتاح> role:<رتبة>",
      description: "منح رتبة صلاحية أمر واحد محدد.",
      permission: "أدمن",
      permissionType: "admin",
      options: [
        { name: "command", type: "نص", required: true, description: "مفتاح الأمر" },
        { name: "role", type: "رتبة", required: true, description: "الرتبة" },
      ],
    },
    {
      id: "config-show",
      name: "/config show",
      syntax: "/config show",
      description: "عرض إعدادات السيرفر الحالية كاملة.",
      permission: "أدمن",
      permissionType: "admin",
      options: [],
    },
  ],
});

categories.push({
  id: "server",
  title: "أنظمة السيرفر",
  description: "ترحيب، رتب، سحوبات، استطلاعات والمزيد",
  commands: [
    {
      id: "server-welcome",
      name: "/server welcome",
      syntax: "/server welcome enabled:<صح/خطأ> [channel] [message]",
      description: "رسائل ترحيب تلقائية. يدعم {user} {username} {server} {membercount}.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "enabled", type: "صح/خطأ", required: true, description: "تفعيل/إيقاف" },
        { name: "channel", type: "قناة", required: false, description: "القناة" },
        { name: "message", type: "نص", required: false, description: "نص الترحيب" },
      ],
    },
    {
      id: "server-goodbye",
      name: "/server goodbye",
      syntax: "/server goodbye enabled:<صح/خطأ> [channel] [message]",
      description: "رسائل وداع تلقائية. يدعم {username} {server}.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "enabled", type: "صح/خطأ", required: true, description: "تفعيل/إيقاف" },
        { name: "channel", type: "قناة", required: false, description: "القناة" },
        { name: "message", type: "نص", required: false, description: "نص الوداع" },
      ],
    },
    {
      id: "server-autorole",
      name: "/server autorole",
      syntax: "/server autorole role:<رتبة> [remove]",
      description: "رتبة تلقائية للأعضاء الجدد.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "role", type: "رتبة", required: true, description: "الرتبة" },
        { name: "remove", type: "صح/خطأ", required: false, description: "إزالة من القائمة" },
      ],
    },
    {
      id: "server-button-role",
      name: "/server button-role",
      syntax: "/server button-role title:<نص> role:<رتبة> label:<نص> [emoji] [unique]",
      description: "زر للحصول على رتبة بالنقر.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "title", type: "نص", required: true, description: "عنوان الرسالة" },
        { name: "role", type: "رتبة", required: true, description: "الرتبة" },
        { name: "label", type: "نص", required: true, description: "نص الزر" },
        { name: "emoji", type: "إيموجي", required: false, description: "إيموجي" },
        { name: "unique", type: "صح/خطأ", required: false, description: "حصرية؟" },
      ],
    },
    {
      id: "server-reaction-role",
      name: "/server reaction-role",
      syntax: "/server reaction-role title:<نص> role:<رتبة> emoji:<إيموجي>",
      description: "رتبة عبر الريأكشن بإيموجي.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "title", type: "نص", required: true, description: "العنوان" },
        { name: "role", type: "رتبة", required: true, description: "الرتبة" },
        { name: "emoji", type: "إيموجي", required: true, description: "الإيموجي" },
      ],
    },
    {
      id: "server-suggest",
      name: "/server suggest",
      syntax: "/server suggest text:<نص>",
      description: "إرسال اقتراح. متاح للجميع.",
      permission: "الكل",
      permissionType: "everyone",
      options: [{ name: "text", type: "نص", required: true, description: "نص الاقتراح" }],
    },
    {
      id: "server-suggest-channel",
      name: "/server suggest-channel",
      syntax: "/server suggest-channel channel:<قناة>",
      description: "تحديد قناة الاقتراحات.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [{ name: "channel", type: "قناة", required: true, description: "القناة" }],
    },
    {
      id: "server-giveaway",
      name: "/server giveaway",
      syntax: "/server giveaway prize:<الجائزة> duration:<مدة> [winners]",
      description: "بدء سحب بتوقيت واختيار فائزين تلقائي.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "prize", type: "نص", required: true, description: "الجائزة" },
        { name: "duration", type: "مدة", required: true, description: "المدة" },
        { name: "winners", type: "رقم 1-20", required: false, description: "عدد الفائزين" },
      ],
    },
    {
      id: "server-poll",
      name: "/server poll",
      syntax: "/server poll question:<سؤال> options:<خيار1|خيار2> [duration]",
      description: "استطلاع رأي تفاعلي.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "question", type: "نص", required: true, description: "السؤال" },
        { name: "options", type: "نص", required: true, description: "خيارات مفصولة بـ |" },
        { name: "duration", type: "مدة", required: false, description: "المدة" },
      ],
    },
    {
      id: "server-stats",
      name: "/server stats",
      syntax: "/server stats",
      description: "قنوات إحصائيات تتحدث تلقائياً.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [],
    },
    {
      id: "server-embed",
      name: "/server embed",
      syntax: "/server embed description:<نص> [title] [color] [image] [footer]",
      description: "إرسال إمبد مخصص.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "description", type: "نص", required: true, description: "المحتوى" },
        { name: "title", type: "نص", required: false, description: "العنوان" },
        { name: "color", type: "hex", required: false, description: "اللون" },
        { name: "image", type: "رابط", required: false, description: "صورة" },
        { name: "footer", type: "نص", required: false, description: "التذييل" },
      ],
    },
    {
      id: "server-autoreact-add",
      name: "/server autoreact-add",
      syntax: "/server autoreact-add channel:<قناة> emoji:<إيموجي>",
      description: "إيموجي تلقائي على كل رسالة في قناة (حتى 5).",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "channel", type: "قناة", required: true, description: "القناة" },
        { name: "emoji", type: "إيموجي", required: true, description: "الإيموجي" },
      ],
    },
    {
      id: "server-autoreact-remove",
      name: "/server autoreact-remove",
      syntax: "/server autoreact-remove channel:<قناة> [emoji]",
      description: "إزالة إيموجي أو كل الإيموجيات من قناة.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "channel", type: "قناة", required: true, description: "القناة" },
        { name: "emoji", type: "إيموجي", required: false, description: "إيموجي محدد" },
      ],
    },
    {
      id: "server-autoreact-list",
      name: "/server autoreact-list",
      syntax: "/server autoreact-list",
      description: "عرض القنوات ذات الرياكشن التلقائي.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [],
    },
  ],
});
categories.push({
  id: "ticket",
  title: "نظام التذاكر",
  description: "لوحات تذاكر، مساعد آلي، وإدارة من داخل القناة",
  commands: [
    {
      id: "ticket-panel",
      name: "/ticket panel",
      syntax: "/ticket panel channel title description category staff_role [style] [max_open] [autoclose] [ai]",
      description: "إنشاء ونشر لوحة تذاكر.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "channel", type: "قناة", required: true, description: "قناة اللوحة" },
        { name: "title", type: "نص", required: true, description: "العنوان" },
        { name: "description", type: "نص", required: true, description: "الوصف" },
        { name: "category", type: "كاتيجوري", required: true, description: "كاتيجوري التذاكر" },
        { name: "staff_role", type: "رتبة", required: true, description: "رتبة الدعم" },
        { name: "style", type: "buttons|select", required: false, description: "نمط الواجهة" },
        { name: "max_open", type: "رقم 1-5", required: false, description: "أقصى تذاكر مفتوحة" },
        { name: "autoclose", type: "مدة", required: false, description: "إغلاق تلقائي" },
        { name: "ai", type: "صح/خطأ", required: false, description: "المساعد الآلي" },
      ],
    },
    {
      id: "ticket-category-add",
      name: "/ticket category-add",
      syntax: "/ticket category-add panel_id key label category [emoji] [description]",
      description: "إضافة نوع/زر للوحة (حتى 25).",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "panel_id", type: "رقم", required: true, description: "معرّف اللوحة" },
        { name: "key", type: "نص", required: true, description: "معرّف فريد" },
        { name: "label", type: "نص", required: true, description: "نص الزر" },
        { name: "category", type: "كاتيجوري", required: true, description: "الكاتيجوري" },
        { name: "emoji", type: "إيموجي", required: false, description: "إيموجي" },
        { name: "description", type: "نص", required: false, description: "وصف قصير" },
      ],
    },
    {
      id: "ticket-category-remove",
      name: "/ticket category-remove",
      syntax: "/ticket category-remove panel_id key",
      description: "حذف نوع من لوحة.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "panel_id", type: "رقم", required: true, description: "معرّف اللوحة" },
        { name: "key", type: "نص", required: true, description: "المعرّف" },
      ],
    },
    {
      id: "ticket-claim",
      name: "/ticket claim",
      syntax: "/ticket claim",
      description: "(داخل التذكرة) استلام التذكرة وإيقاف المساعد الآلي.",
      permission: "موظفين",
      permissionType: "staff",
      options: [],
    },
    {
      id: "ticket-unclaim",
      name: "/ticket unclaim",
      syntax: "/ticket unclaim",
      description: "(داخل التذكرة) إلغاء الاستلام وإعادة المساعد الآلي.",
      permission: "موظفين",
      permissionType: "staff",
      options: [],
    },
    {
      id: "ticket-close",
      name: "/ticket close",
      syntax: "/ticket close",
      description: "(داخل التذكرة) إغلاق التذكرة.",
      permission: "موظفين",
      permissionType: "staff",
      options: [],
    },
    {
      id: "ticket-reopen",
      name: "/ticket reopen",
      syntax: "/ticket reopen",
      description: "إعادة فتح تذكرة مغلقة.",
      permission: "موظفين",
      permissionType: "staff",
      options: [],
    },
    {
      id: "ticket-add",
      name: "/ticket add",
      syntax: "/ticket add user:<عضو>",
      description: "(داخل التذكرة) إضافة عضو.",
      permission: "موظفين",
      permissionType: "staff",
      options: [{ name: "user", type: "عضو", required: true, description: "العضو" }],
    },
    {
      id: "ticket-remove",
      name: "/ticket remove",
      syntax: "/ticket remove user:<عضو>",
      description: "(داخل التذكرة) إزالة عضو.",
      permission: "موظفين",
      permissionType: "staff",
      options: [{ name: "user", type: "عضو", required: true, description: "العضو" }],
    },
    {
      id: "ticket-transfer",
      name: "/ticket transfer",
      syntax: "/ticket transfer user:<موظف>",
      description: "(داخل التذكرة) نقل المسؤولية لموظف آخر.",
      permission: "موظفين",
      permissionType: "staff",
      options: [{ name: "user", type: "عضو", required: true, description: "الموظف" }],
    },
    {
      id: "ticket-kb-add",
      name: "/ticket kb-add",
      syntax: "/ticket kb-add title:<نص> content:<نص>",
      description: "إضافة مقال لقاعدة معرفة المساعد الآلي.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [
        { name: "title", type: "نص", required: true, description: "العنوان" },
        { name: "content", type: "نص", required: true, description: "المحتوى" },
      ],
    },
    {
      id: "ticket-ai-status",
      name: "/ticket ai-status",
      syntax: "/ticket ai-status",
      description: "التحقق من حالة تكامل الذكاء الاصطناعي.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [],
    },
    {
      id: "ticket-list",
      name: "/ticket list",
      syntax: "/ticket list",
      description: "عرض كل لوحات التذاكر.",
      permission: "موظفين / أدمن",
      permissionType: "staff",
      options: [],
    },
  ],
});

categories.push({
  id: "invites",
  title: "حماية الدعوات",
  description: "عدّ دعوات حقيقي مع كشف الحسابات الوهمية",
  commands: [
    {
      id: "invites",
      name: "/invites",
      syntax: "/invites [user:<عضو>]",
      description: "عرض عدد الدعوات الحقيقي مع كشف الحسابات الوهمية (عمر أقل من 4 أشهر وبدون صورة). الافتراضي: أنت.",
      permission: "الكل",
      permissionType: "everyone",
      options: [{ name: "user", type: "عضو", required: false, description: "العضو (افتراضي أنت)" }],
    },
  ],
});

categories.push({
  id: "games",
  title: "الألعاب الترفيهية",
  description: "ألعاب نصية ونظام نقاط",
  commands: [],
});

export const gamesDescription =
  "العب ألعاب نصية سريعة مباشرة في الشات — أسرع، فكك الحروف، لغز، عواصم، أعلام، اعكس الكلمة، وتحديات حساب عبر /games play، بالإضافة إلى روليت جماعي بالإقصاء، نظام نقاط ومتصدرين، وأوامر مزح خفيفة مثل الصفعة والاختراق الوهمي ونسبة التوافق.";
