/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandsRouteImport } from './routes/commands'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuickstartRouteImport } from './routes/quickstart'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardGuildIdRouteRouteImport } from './routes/dashboard/$guildId/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDiscordAuthorizeRouteImport } from './routes/api/discord/authorize'
import { Route as ApiDiscordCallbackRouteImport } from './routes/api/discord/callback'
import { Route as DashboardGuildIdIndexRouteImport } from './routes/dashboard/$guildId/index'
import { Route as DashboardGuildIdAutomodRouteImport } from './routes/dashboard/$guildId/automod'
import { Route as DashboardGuildIdCommandsRouteImport } from './routes/dashboard/$guildId/commands'
import { Route as DashboardGuildIdGamesRouteImport } from './routes/dashboard/$guildId/games'
import { Route as DashboardGuildIdInvitesRouteImport } from './routes/dashboard/$guildId/invites'
import { Route as DashboardGuildIdModerationRouteImport } from './routes/dashboard/$guildId/moderation'
import { Route as DashboardGuildIdServerRouteImport } from './routes/dashboard/$guildId/server'
import { Route as DashboardGuildIdSettingsRouteImport } from './routes/dashboard/$guildId/settings'
import { Route as DashboardGuildIdTicketsRouteImport } from './routes/dashboard/$guildId/tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsRoute = CommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickstartRoute = QuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdRouteRoute = DashboardGuildIdRouteRouteImport.update({
  id: '/dashboard/$guildId',
  path: '/dashboard/$guildId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordAuthorizeRoute = ApiDiscordAuthorizeRouteImport.update({
  id: '/api/discord/authorize',
  path: '/api/discord/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordCallbackRoute = ApiDiscordCallbackRouteImport.update({
  id: '/api/discord/callback',
  path: '/api/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdIndexRoute = DashboardGuildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardGuildIdRouteRoute,
} as any)
const DashboardGuildIdAutomodRoute = DashboardGuildIdAutomodRouteImport.update({
  id: '/automod',
  path: '/automod',
  getParentRoute: () => DashboardGuildIdRouteRoute,
} as any)
const DashboardGuildIdCommandsRoute =
  DashboardGuildIdCommandsRouteImport.update({
    id: '/commands',
    path: '/commands',
    getParentRoute: () => DashboardGuildIdRouteRoute,
  } as any)
const DashboardGuildIdGamesRoute = DashboardGuildIdGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => DashboardGuildIdRouteRoute,
} as any)
const DashboardGuildIdInvitesRoute = DashboardGuildIdInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => DashboardGuildIdRouteRoute,
} as any)
const DashboardGuildIdModerationRoute =
  DashboardGuildIdModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => DashboardGuildIdRouteRoute,
  } as any)
const DashboardGuildIdServerRoute = DashboardGuildIdServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => DashboardGuildIdRouteRoute,
} as any)
const DashboardGuildIdSettingsRoute =
  DashboardGuildIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardGuildIdRouteRoute,
  } as any)
const DashboardGuildIdTicketsRoute = DashboardGuildIdTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DashboardGuildIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quickstart': typeof QuickstartRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/discord/authorize': typeof ApiDiscordAuthorizeRoute
  '/api/discord/callback': typeof ApiDiscordCallbackRoute
  '/dashboard/$guildId/automod': typeof DashboardGuildIdAutomodRoute
  '/dashboard/$guildId/commands': typeof DashboardGuildIdCommandsRoute
  '/dashboard/$guildId/games': typeof DashboardGuildIdGamesRoute
  '/dashboard/$guildId/invites': typeof DashboardGuildIdInvitesRoute
  '/dashboard/$guildId/moderation': typeof DashboardGuildIdModerationRoute
  '/dashboard/$guildId/server': typeof DashboardGuildIdServerRoute
  '/dashboard/$guildId/settings': typeof DashboardGuildIdSettingsRoute
  '/dashboard/$guildId/tickets': typeof DashboardGuildIdTicketsRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quickstart': typeof QuickstartRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/discord/authorize': typeof ApiDiscordAuthorizeRoute
  '/api/discord/callback': typeof ApiDiscordCallbackRoute
  '/dashboard/$guildId/automod': typeof DashboardGuildIdAutomodRoute
  '/dashboard/$guildId/commands': typeof DashboardGuildIdCommandsRoute
  '/dashboard/$guildId/games': typeof DashboardGuildIdGamesRoute
  '/dashboard/$guildId/invites': typeof DashboardGuildIdInvitesRoute
  '/dashboard/$guildId/moderation': typeof DashboardGuildIdModerationRoute
  '/dashboard/$guildId/server': typeof DashboardGuildIdServerRoute
  '/dashboard/$guildId/settings': typeof DashboardGuildIdSettingsRoute
  '/dashboard/$guildId/tickets': typeof DashboardGuildIdTicketsRoute
  '/dashboard/$guildId': typeof DashboardGuildIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quickstart': typeof QuickstartRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/discord/authorize': typeof ApiDiscordAuthorizeRoute
  '/api/discord/callback': typeof ApiDiscordCallbackRoute
  '/dashboard/$guildId/automod': typeof DashboardGuildIdAutomodRoute
  '/dashboard/$guildId/commands': typeof DashboardGuildIdCommandsRoute
  '/dashboard/$guildId/games': typeof DashboardGuildIdGamesRoute
  '/dashboard/$guildId/invites': typeof DashboardGuildIdInvitesRoute
  '/dashboard/$guildId/moderation': typeof DashboardGuildIdModerationRoute
  '/dashboard/$guildId/server': typeof DashboardGuildIdServerRoute
  '/dashboard/$guildId/settings': typeof DashboardGuildIdSettingsRoute
  '/dashboard/$guildId/tickets': typeof DashboardGuildIdTicketsRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commands'
    | '/features'
    | '/login'
    | '/privacy'
    | '/quickstart'
    | '/support'
    | '/terms'
    | '/dashboard/$guildId'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/discord/authorize'
    | '/api/discord/callback'
    | '/dashboard/$guildId/automod'
    | '/dashboard/$guildId/commands'
    | '/dashboard/$guildId/games'
    | '/dashboard/$guildId/invites'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/server'
    | '/dashboard/$guildId/settings'
    | '/dashboard/$guildId/tickets'
    | '/dashboard/$guildId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commands'
    | '/features'
    | '/login'
    | '/privacy'
    | '/quickstart'
    | '/support'
    | '/terms'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/discord/authorize'
    | '/api/discord/callback'
    | '/dashboard/$guildId/automod'
    | '/dashboard/$guildId/commands'
    | '/dashboard/$guildId/games'
    | '/dashboard/$guildId/invites'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/server'
    | '/dashboard/$guildId/settings'
    | '/dashboard/$guildId/tickets'
    | '/dashboard/$guildId'
  id:
    | '__root__'
    | '/'
    | '/commands'
    | '/features'
    | '/login'
    | '/privacy'
    | '/quickstart'
    | '/support'
    | '/terms'
    | '/dashboard/$guildId'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/discord/authorize'
    | '/api/discord/callback'
    | '/dashboard/$guildId/automod'
    | '/dashboard/$guildId/commands'
    | '/dashboard/$guildId/games'
    | '/dashboard/$guildId/invites'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/server'
    | '/dashboard/$guildId/settings'
    | '/dashboard/$guildId/tickets'
    | '/dashboard/$guildId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandsRoute: typeof CommandsRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  QuickstartRoute: typeof QuickstartRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  DashboardGuildIdRouteRoute: typeof DashboardGuildIdRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDiscordAuthorizeRoute: typeof ApiDiscordAuthorizeRoute
  ApiDiscordCallbackRoute: typeof ApiDiscordCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quickstart': {
      id: '/quickstart'
      path: '/quickstart'
      fullPath: '/quickstart'
      preLoaderRoute: typeof QuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId': {
      id: '/dashboard/$guildId'
      path: '/dashboard/$guildId'
      fullPath: '/dashboard/$guildId'
      preLoaderRoute: typeof DashboardGuildIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord/authorize': {
      id: '/api/discord/authorize'
      path: '/api/discord/authorize'
      fullPath: '/api/discord/authorize'
      preLoaderRoute: typeof ApiDiscordAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord/callback': {
      id: '/api/discord/callback'
      path: '/api/discord/callback'
      fullPath: '/api/discord/callback'
      preLoaderRoute: typeof ApiDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/': {
      id: '/dashboard/$guildId/'
      path: '/'
      fullPath: '/dashboard/$guildId/'
      preLoaderRoute: typeof DashboardGuildIdIndexRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/automod': {
      id: '/dashboard/$guildId/automod'
      path: '/automod'
      fullPath: '/dashboard/$guildId/automod'
      preLoaderRoute: typeof DashboardGuildIdAutomodRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/commands': {
      id: '/dashboard/$guildId/commands'
      path: '/commands'
      fullPath: '/dashboard/$guildId/commands'
      preLoaderRoute: typeof DashboardGuildIdCommandsRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/games': {
      id: '/dashboard/$guildId/games'
      path: '/games'
      fullPath: '/dashboard/$guildId/games'
      preLoaderRoute: typeof DashboardGuildIdGamesRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/invites': {
      id: '/dashboard/$guildId/invites'
      path: '/invites'
      fullPath: '/dashboard/$guildId/invites'
      preLoaderRoute: typeof DashboardGuildIdInvitesRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/moderation': {
      id: '/dashboard/$guildId/moderation'
      path: '/moderation'
      fullPath: '/dashboard/$guildId/moderation'
      preLoaderRoute: typeof DashboardGuildIdModerationRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/server': {
      id: '/dashboard/$guildId/server'
      path: '/server'
      fullPath: '/dashboard/$guildId/server'
      preLoaderRoute: typeof DashboardGuildIdServerRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/settings': {
      id: '/dashboard/$guildId/settings'
      path: '/settings'
      fullPath: '/dashboard/$guildId/settings'
      preLoaderRoute: typeof DashboardGuildIdSettingsRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/tickets': {
      id: '/dashboard/$guildId/tickets'
      path: '/tickets'
      fullPath: '/dashboard/$guildId/tickets'
      preLoaderRoute: typeof DashboardGuildIdTicketsRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
  }
}

interface DashboardGuildIdRouteRouteChildren {
  DashboardGuildIdAutomodRoute: typeof DashboardGuildIdAutomodRoute
  DashboardGuildIdCommandsRoute: typeof DashboardGuildIdCommandsRoute
  DashboardGuildIdGamesRoute: typeof DashboardGuildIdGamesRoute
  DashboardGuildIdInvitesRoute: typeof DashboardGuildIdInvitesRoute
  DashboardGuildIdModerationRoute: typeof DashboardGuildIdModerationRoute
  DashboardGuildIdServerRoute: typeof DashboardGuildIdServerRoute
  DashboardGuildIdSettingsRoute: typeof DashboardGuildIdSettingsRoute
  DashboardGuildIdTicketsRoute: typeof DashboardGuildIdTicketsRoute
  DashboardGuildIdIndexRoute: typeof DashboardGuildIdIndexRoute
}

const DashboardGuildIdRouteRouteChildren: DashboardGuildIdRouteRouteChildren = {
  DashboardGuildIdAutomodRoute: DashboardGuildIdAutomodRoute,
  DashboardGuildIdCommandsRoute: DashboardGuildIdCommandsRoute,
  DashboardGuildIdGamesRoute: DashboardGuildIdGamesRoute,
  DashboardGuildIdInvitesRoute: DashboardGuildIdInvitesRoute,
  DashboardGuildIdModerationRoute: DashboardGuildIdModerationRoute,
  DashboardGuildIdServerRoute: DashboardGuildIdServerRoute,
  DashboardGuildIdSettingsRoute: DashboardGuildIdSettingsRoute,
  DashboardGuildIdTicketsRoute: DashboardGuildIdTicketsRoute,
  DashboardGuildIdIndexRoute: DashboardGuildIdIndexRoute,
}

const DashboardGuildIdRouteRouteWithChildren =
  DashboardGuildIdRouteRoute._addFileChildren(
    DashboardGuildIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandsRoute: CommandsRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  QuickstartRoute: QuickstartRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  DashboardGuildIdRouteRoute: DashboardGuildIdRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDiscordAuthorizeRoute: ApiDiscordAuthorizeRoute,
  ApiDiscordCallbackRoute: ApiDiscordCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
